### PR TITLE
The Russian translation

### PR DESCRIPTION
**Pull request by Futyn-Maker**
Here is the Russian translation of the addon. The UI-file and the documentation.

The translated manifest.ini is here:

https://www.dropbox.com/s/u1sti5c6zqxa2wj/manifest.ini?dl=1

### CODE REVIEW

**Comment by Futyn-Maker** [comment]
Will You build the new development version? Or You have the planned release date?

**Comment by ibrahim-s** [comment]
Really until now, I do not know where is the problem
building a development version will not make a difference
may be the problem in my nvda.po, or in your translation of the file
and the error message is not obvious enough
I just will still try
thanks

**Comment by Futyn-Maker** [comment]
Well, in my NVDA 2020.3 the addon works absolutely correct with my translation. What's the error message?

**Comment by Futyn-Maker** [comment]
Very strange... When I try to build it by Scons, the build crashes when creating documentation (Markdown to HTML). Is it Your problem, too?

**Comment by Futyn-Maker** [comment]
@ibrahim-s I've found the error! In the first line of my nvda.po-file there's no number sign (\#) as a comment line. Stupid mistake :-)

**Comment by ibrahim-s** [comment]
Now the build has succeeded
the only change I made in your nvda.po file is setting of encoding of 
source language to utf-8
and that was not set.
this is the link of the addon with Russian translation:
https://github.com/ibrahim-s/trainingNvdaCommands/releases/download/v2.1/trainingKeyboardCommands-2.1.nvda-addon
thank you for bearing with me
and as you know it is very hard to test a language that you do not know
So if in your testing of the addon , you find bugs or problems , please 
tell me.
All the best
ibrahim.

**Comment by Futyn-Maker** [comment]
Thanks :)

**Comment by Futyn-Maker** [comment]
All OK, but it makes sense to update the download links in doc-files...

**Pull request merged**
